name: Sincronizar Quiniela
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: node sync.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}